# cloudbuild.yaml - Google Cloud Build Configuration File

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/cloud-computing-448017/uma-100994095/app:$COMMIT_SHA'  # Ensure [PROJECT_ID] and [ARTIFACT_REGISTRY_NAME] are correct
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/cloud-computing-448017/uma-100994095/app:$COMMIT_SHA'  # Ensure [PROJECT_ID] and [ARTIFACT_REGISTRY_NAME] are correct

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app-service'  # Replace with your Cloud Run service name
      - '--image'
      - 'us-central1-docker.pkg.dev/cloud-computing-448017/uma-100994095/app:$COMMIT_SHA'  # Ensure correct image path
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/cloud-computing-448017/uma-100994095/app:$COMMIT_SHA'  # Ensure [PROJECT_ID] and [ARTIFACT_REGISTRY_NAME] are correct

logsBucket: "gs://logs-bucket-uma/"  # Use the correct logs bucket for your project

options:
  logging: GCS_ONLY  # Ensures build logs are stored in a Cloud Storage bucket
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # Creates a new bucket in the same region as the project to store logs
