# cloudbuild.yaml - Google Cloud Build Configuration File

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/cloud-computing-448017/uma-100994095/app:$COMMIT_SHA'  # Ensure [PROJECT_ID] and [ARTIFACT_REGISTRY_NAME] are correct
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/cloud-computing-448017/uma-100994095/app:$COMMIT_SHA'  # Ensure [PROJECT_ID] and [ARTIFACT_REGISTRY_NAME] are correct

logsBucket: "gs://logs-bucket-uma/"  # Moved this to the correct location

options:
  logging: GCS_ONLY  # Ensures build logs are stored in a Cloud Storage bucket
